

permissions:
  contents: write   # allow Actions to push commits

on:
  schedule:
    - cron: '30 4 * * *'  # Github timezone is UTC, this will be 10 AM IST everyday 
  workflow_dispatch: {}     # allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python python/news.py

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or whatever version you need

      - name: Install dependencies
        run: npm install   # (or pnpm/yarn if you use that)

      - name: Run script
        run: node generate-static.js

      - name: Commit and push JSON + HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update news + HTML $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
