

permissions:
  contents: write   # allow Actions to push commits

on:
  schedule:
    - cron: '0 10 * * *'  # every 2 hours
  workflow_dispatch: {}     # allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python python/news.py

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/news/news_articles/news-data.json
          git commit -m "chore: update news $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
